alias ls="ls -F --color "
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias rm='rm -vi'
alias mv='mv -vi'
alias cp='cp -vi'
alias op=gnome-open

# searches for given string in filenames in current and all subdirectories
function s { find . -name "*$1*" 2>/dev/null; }
# searches for given filename exactly in current and all subdirectories
function ss { find . -name "$1" 2>/dev/null; }

# git
alias gst='git status'
alias ga='git add -p'
alias gc='git commit -v'
alias gco='git checkout'

# Bookmarks solution:
# https://www.datascienceworkshops.com/blog/quickly-navigate-your-filesystem-from-the-command-line/
export MARKPATH=$HOME/.marks
function jump { cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"; }
function mark { mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"; }
function unmark { rm -i "$MARKPATH/$1"; }
function marks { ls -l "$MARKPATH" | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo; }
